In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0,5,26)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(10)

array([0.4435132 , 0.33439699, 0.31392881, 0.13394109, 0.17718017,
       0.69439883, 0.44228875, 0.80573385, 0.37265757, 0.22041491])

In [29]:
np.random.randn(10)

array([-1.62049251, -0.9780233 ,  2.02897265,  0.80071191,  0.13735661,
        0.91713126,  0.54796101,  1.40577609,  1.10192928, -1.43126897])

In [30]:
np.random.randn(5,5)

array([[ 0.00347892, -0.01960265, -0.38683779,  1.94979907,  2.0167188 ],
       [-0.77260814, -0.89498892, -0.17739024, -0.50139567, -0.42376553],
       [ 1.40028069, -1.01913648,  0.46189626, -1.08768192, -1.36219021],
       [ 1.22261467,  0.86409633,  0.3858254 ,  0.6484116 , -1.28594775],
       [ 0.23825524,  0.03569553,  1.70696818,  0.35990643,  0.36588017]])

In [35]:
np.random.randint(1,100,10)

array([73,  5, 40, 64,  8,  7, 89, 65,  6, 10])

In [43]:
np.random.seed(10)
np.random.randint(1,9,(3,3))

array([[2, 6, 5],
       [8, 1, 2],
       [4, 5, 2]])

In [55]:
arr = np.arange(24)
ranarr = np.random.randint(0,50,10)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
ranarr

array([49, 13,  5, 13, 25, 13, 28, 22, 30, 30])

In [53]:
arr2 = arr.reshape(8,3)

In [54]:
arr2.shape #size of the matrix/list

(8, 3)

In [59]:
ranarr.max() #highest element

49

In [60]:
ranarr.min() #lowest element

5

In [61]:
ranarr.argmin() #pang ilan sa list

2

In [62]:
arr.dtype #type of element

dtype('int32')

In [64]:
arr3 = np.random.rand(5,5)
arr3

array([[0.87574449, 0.2960687 , 0.13129105, 0.84281793, 0.6590363 ],
       [0.5954396 , 0.4363537 , 0.35625033, 0.58713093, 0.14947134],
       [0.1712386 , 0.39716452, 0.63795156, 0.37251995, 0.00240676],
       [0.54881636, 0.12697184, 0.07979268, 0.2350386 , 0.65996495],
       [0.21495319, 0.20304662, 0.38286511, 0.2248728 , 0.1146488 ]])

In [65]:
arr3.dtype

dtype('float64')

In [70]:
arr4 = np.arange(0,11)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr4[9]

9

In [78]:
arr4[1:5]

array([1, 2, 3, 4])

In [73]:
arr5 = np.linspace(0,5,10)
arr5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [75]:
arr5[9]

5.0

In [79]:
arr5[1:5]

array([0.55555556, 1.11111111, 1.66666667, 2.22222222])

In [83]:
my_list = [0,1,2,3,4,5,6,7,8,9,10]
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [84]:
my_list[0:5]

[0, 1, 2, 3, 4]

In [87]:
arr5[1:5] = 100
arr5

array([  0.        , 100.        , 100.        , 100.        ,
       100.        ,   2.77777778,   3.33333333,   3.88888889,
         4.44444444,   5.        ])

In [90]:
for i in range(0,6):
    my_list[i] = 100
my_list

[100, 100, 100, 100, 100, 100, 6, 7, 8, 9, 10]

In [91]:
arr6 = np.array([1,2,3,4])
arr6

array([1, 2, 3, 4])

In [95]:
arr2d = np.array(([1, 2, 3],[4,5,6,],[7,8,9]))
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
arr2d[1][0]

4

In [97]:
arr2d[1,0]

4

In [98]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [99]:
arr2d[:2,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
arr2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [120]:
arr2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [121]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [122]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [124]:
arr[arr%4]

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3])

In [126]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [131]:
arr2 = np.arange(11,35)
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34])

In [132]:
arr + arr2

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57])

In [135]:
arr2d.mean()

5.0